// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfV1pfSbDDnSctglukj8AZoz-BoRRZpqI',
    appId: '1:1012023695416:web:240b1f3278c98e25026ecd',
    messagingSenderId: '1012023695416',
    projectId: 'skillora-7cee4',
    authDomain: 'skillora-7cee4.firebaseapp.com',
    storageBucket: 'skillora-7cee4.firebasestorage.app',
    measurementId: 'G-SRHPH07S6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXmO0IdfWCKtM1RJ1eWMP0jRBSzFCxY1Q',
    appId: '1:1012023695416:android:89f38415b16e4ef7026ecd',
    messagingSenderId: '1012023695416',
    projectId: 'skillora-7cee4',
    storageBucket: 'skillora-7cee4.firebasestorage.app',
  );
}
